### ISSUE TITLE
How to use content-aware fill within the API?

### ISSUE THREAD

**Issue by samp50** [AdobeDocs/photoshop-api-docs#63]
I am looking to use Photoshop's [content-aware fill](https://helpx.adobe.com/photoshop/using/content-aware-fill.html) within the API. I assume this behavior would be under the "edit objects" part of the docs, but I am not sure the what's the proper syntax when trying to use that function. Does anyone know how to use this Photoshop function in the API?

**Comment by johnleetran** [comment]
For those whom find this post, now in pre-release, the ability to record and playback Photoshop Actions with Photoshop APIs.  You can record actions in Photoshop (content-aware fill or any other feature).  Please see for docs and notes

https://github.com/AdobeDocs/photoshop-api-docs-pre-release#photoshop-actions
