### ISSUE TITLE
/documentManifest API throwing an error for PSD files larger than 100 MB.

### ISSUE THREAD

**Issue by achal648** [AdobeDocs/photoshop-api-docs#64]
I am getting the below error when trying the API with PSD files larger than 100 MB, but for smaller files, it is working perfectly.

{
  "input": "files/xyz.psd",
  "status": "failed",
  "created": "2020-10-06T06:59:01.852Z",
  "modified": "2020-10-06T06:59:11.854Z",
  "errors": {
                 "code": 500,
                 "title": "PIE has thrown an exception",
                 "type": "InternalServiceError"
                }
}

Is there any size limitation?

**Comment by johnleetran** [comment]
Hello @achal648, 100MB should not be a problem.  Are you trying to generate layer `thumbnails` with the documentManifest call?  If so, could you check if you have PDF or Illustrator smartObjects?  We currently have a known bug that is unable to correctly generate renditions with PDF or Illustrator smartObjects.

**Comment by achal648** [comment]
Thanks, @johnleetran for the prompt response. I was not trying to generate layer thumbnails, just the layer info. I tried with a few larger files and I got a response for one of them, but still failing for the rest. So size is definitely not an issue. Is there any way that I could generate just the layer info for PSD files which have illustrator smartObjects?

**Comment by johnleetran** [comment]
hmmm...you should be able to generate just the layer info even with an illustrator smartObject.  For example,

```
curl -H "Authorization: Bearer $token" -H "x-api-key: $api_key" https://image-stage.adobe.io/pie/psdService/documentManifest -d '{
  "inputs": [
    {
      "href": "https://jotran-pie-in-the-sky-automation.s3.amazonaws.com/psd/astro-stars.psd",
      "storage": "external"
    }
  ]
}'
```

**Comment by achal648** [comment]
Still getting the same response.

```
curl -H "Authorization: Bearer $token" -H "x-api-key: $api_key" https://image.adobe.io/pie/psdService/documentManifest -d '{
  "inputs": [
    {
      "href": "files/sample.psd",
      "storage": "adobe"
    }
  ]
}'
```

```
"outputs": [
        {
            "input": "files/sample.psd",
            "status": "failed",
            "created": "2020-10-07T04:59:27.345Z",
            "modified": "2020-10-07T05:00:40.989Z",
            "errors": {
                "code": 500,
                "title": "PIE has thrown an exception",
                "type": "InternalServiceError"
            }
        }
    ]
```

**Comment by johnleetran** [comment]
@achal648 Thanks for you patients, we have deploy a fix to at least get you a manifest PSD with AI or PDFs.
