### ISSUE TITLE
How to hide a layer?

### ISSUE THREAD

**Issue by kratosvn** [AdobeDocs/photoshop-api-docs#81]
### Expected Behaviour
- I want to hide a laye from pts api

### Actual Behaviour
- I read your document from https://www.adobe.io/photoshop/photoshop-api-docs/api/#tag/Photoshop, but i cant see how to hide a layer

**Comment by kratosvn** [comment]
@johnleetran can you help me check this issue? thank you

**Comment by johnleetran** [comment]
Hello @kratosvn,

In order to hide a layer, you can use the `visible` field within the `options.layers[]` data structure.  For example,

```
{
    "inputs": [...],
    "options": {
        "layers" : [
            {
                "name": "YOUR_LAYER_NAME",  
                "visible": false
            }
        ]
    },
    "outputs": [...]
}
```

**Comment by johnleetran** [comment]
Closing, further help can be found by emailing psdservices@adobe.com
